### ISSUE TITLE
[Feature Request] Allow custom jdbc URL

### ISSUE THREAD

**Issue by zly2006** [QuiltServerTools/Ledger#254]
### Is your feature request related to a problem?

I have a backup tool that auto backs up the entire world folder. ledger's database take a lot of disk usage so i wanto to change its database location.

### Describe the solution you'd like.

```toml
[database]
url = "jdbc:sqlite:./sample.db" # . refers to server root, not world folder
```

### Describe alternatives you've considered.

 n/a

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.
